### ISSUE TITLE
Broken -u in node v5.4.0 (or with some updated module)

### ISSUE THREAD

**Issue by metalim** [dylang/npm-check#73]
npm-check v4.1.3
OSX: 10.11.2
Interactive mode works fine with v5.3.0
In v5.4.0 I get:

```
└> npm-check -u
[npm-check] TypeError: content.split is not a function
    at forceLineReturn (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/inquirer/lib/utils/screen-manager.js:133:39)
    at ScreenManager.render (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/inquirer/lib/utils/screen-manager.js:61:21)
    at Prompt.render (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/lib/prompts/alt-checkbox.js:117:15)
    at Prompt._run (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/lib/prompts/alt-checkbox.js:82:8)
    at Prompt.run (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/inquirer/lib/prompts/base.js:55:8)
    at Object.<anonymous> (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/inquirer/lib/ui/prompt.js:84:12)
    at module.exports (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/run-async/index.js:15:21)
    at AnonymousObservable.__subscribe (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/inquirer/lib/utils/utils.js:16:7)
    at AnonymousObservable.tryCatcher (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:63:31)
    at setDisposable (/Users/metalim/.nvm/versions/node/v5.4.0/lib/node_modules/npm-check/node_modules/rx-lite/rx.lite.js:5741:44)
```

**Comment by prestonvanloon** [comment]
Experiencing same thing in Node 4.2.4 with npm 2.14.12

**Comment by dylang** [comment]
Thanks for reporting this. 

Can you provide the output for this:

```
npm-check --debug
```

Thanks!

**Comment by dylang** [comment]
Also, are you using `nvm` to switch node versions? If you are not, can you try re-installing `npm-check`?

**Comment by dylang** [comment]
Update: I'm able to reproduce the problem locally when installing `npm-check` with `npm@3`. 

If you figure out a fix for this let me know.

**Comment by dylang** [comment]
I figured out the problem and should have a fix published some time today.

**Comment by dylang** [comment]
new version published! Thanks again for reporting the issue.
